server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
        - id: customer-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.perfect: TRACE