server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/customer/**
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true