server:
  port: 8070


spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.perfect: TRACE
    com.netflix.hystrix: DEBUG