spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/payment
    username: rfperfect
  jpa:
    show-sql: false
  zipkin:
    base-url: http://localhost:9411
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.perfect: INFO

#server:
#  ssl:
#    key-alias: ms-secure
#    key-store-type: JKS
#    key-password:
#    key-store: