server:
  port: 8091

spring:
  application:
    name: payment-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/payment
    username: rfperfect
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: test
  security:
    user:
      name: perfect
      password: ms-secure

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.perfect: TRACE
